apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
  namespace: counter-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0d29fa0e49dc39023,subnet-008b8f6d7715abc73"