{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: counter-frontend-pdb
  labels:
    {{- include "counter-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "counter-service.selectorLabels" . | nindent 6 }}
      component: frontend
{{- end }}