apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: counter-service
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: counter-db-secret
  namespace: counter-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: counter-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: arn:aws:secretsmanager:eu-west-2:630943284793:secret:rds!db-bbf5f26d-e3e3-4819-8a8c-6929cb818470-rfB5Ao
        property: username
    - secretKey: password
      remoteRef:
        key: arn:aws:secretsmanager:eu-west-2:630943284793:secret:rds!db-bbf5f26d-e3e3-4819-8a8c-6929cb818470-rfB5Ao
        property: password