apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: counter-service

resources:
  - deployment.yml
  - service.yml
  - configmap.yml
  - postgres.yaml
  - token_job.yml

commonLabels:
  app: counter-service
