apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: counter-backend-pdb
  namespace: counter-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: counter-service
      component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: counter-frontend-pdb
  namespace: counter-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: counter-service
      component: frontend