apiVersion: v1
kind: Service
metadata:
  name: counter-backend
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
spec:
  type: ClusterIP
  selector:
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: counter-postgres
spec:
  type: ClusterIP
  selector:
    component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432