apiVersion: v1
kind: Service
metadata:
  name: counter-backend
  namespace: counter-service
  labels:
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    component: backend
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
  namespace: counter-service
  labels:
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    component: frontend